### ISSUE TITLE
Map value type and other concerns.

### ISSUE THREAD

**Issue by lambdista** [Verizon/knobs#23]
Hi,
I gave knobs a spin and this are my concerns:
1. Typesage Config (TSC) allows you to use lists of maps, e.g. [{a = 42, b = "hello"}, {a = 24, b = "world"}]. When I tried to load a `Config` using the `Typesafe` extension I got an error since in the `CfgValue` AST there's no case for a `Map`-like object. Is there a good reason for that? I mean, apart from the TSC integration I think it would be useful being able to define a list of maps in the config file.
2. I think the extension for TSC should be changed. At the moment the `Typesafe` object just expose a `config` method type which, internally, loads a TSC object using the default behaviour, that is `ConfigFactory.load`. Since you can use other methods to load a TSC wouldn't it make sense exposing a method which accepts a TSC object and returns a knobs `Config`? Of course keeping also the `config` method type which uses the default behaviour.
3. `Config.require[A:Configured]` throws a `KeyError` exception if the key is not found and this is reasonable. The problem is it throws that exception even if the key is present but the `CfgValue` could have not been converted into `A`. I think it should be changed to give it a more reasonable behaviour.
4. There's no instance for `Configured[Long]`. Is there a good reason for that?

Once I was there playing with the toy I tried to solve the four issues aforementioned and, apparently, I made it. I updated the docs too to include the _lists of maps_ value type.

Let me know if you may be interested in a PR of all or some of these new features.

P.S.: This is a REPL session of the new features, where `objlist.cfg` is a simple config file as in:

```
objList = [{a = 42, b = 24}, {a = 1, b = 2}]

long = 10000000000

hi = "hello"
```

REPL session:

``` scala
scala> import java.io.File
import java.io.File

scala> import knobs._
import knobs._

scala> import knobs.{Required,FileResource,Config}
import knobs.{Required, FileResource, Config}

scala> import scalaz.concurrent.Task
import scalaz.concurrent.Task

scala> val cfg: Task[Config] = knobs.loadImmutable(Required(FileResource(new File("core/src/test/resources/objlist.cfg"))) :: Nil)
cfg: scalaz.concurrent.Task[knobs.Config] = scalaz.concurrent.Task@26b3524c

scala> val config = cfg.run
config: knobs.Config = Config(Map(objList -> CfgList(List(CfgMap(Map(a -> CfgNumber(42.0), b -> CfgNumber(24.0))), CfgMap(Map(a -> CfgNumber(1.0), b -> CfgNumber(2.0))))), long -> CfgNumber(1.0E10), hi -> CfgText(hello)))

scala> config.require[List[Map[String, Int]]]("objList")
res0: List[Map[String,Int]] = List(Map(a -> 42, b -> 24), Map(a -> 1, b -> 2))

scala> config.require[List[CfgValue]]("objList")
res1: List[knobs.CfgValue] = List(CfgMap(Map(a -> CfgNumber(42.0), b -> CfgNumber(24.0))), CfgMap(Map(a -> CfgNumber(1.0), b -> CfgNumber(2.0))))

scala> config.require[CfgValue]("objList")
res2: knobs.CfgValue = CfgList(List(CfgMap(Map(a -> CfgNumber(42.0), b -> CfgNumber(24.0))), CfgMap(Map(a -> CfgNumber(1.0), b -> CfgNumber(2.0)))))

scala> res2.pretty
res3: String = [{a = 42.0, b = 24.0}, {a = 1.0, b = 2.0}]

scala> config.require[Long]("long")
res4: Long = 10000000000

scala> config.require[Int]("missingKey")
knobs.KeyError: No such key: missingKey
        at knobs.Config$$anonfun$1.apply(Config.scala:40)
        at knobs.Config$$anonfun$1.apply(Config.scala:40)
        ...

scala> config.require[Int]("hi")
knobs.ConversionError: Could not convert "hello" to int
        at knobs.Config$$anonfun$require$1.apply(Config.scala:41)
        at knobs.Config$$anonfun$require$1.apply(Config.scala:41)
        ...
```

**Comment by timperrett** [comment]
For `2`, sure thats an option; just not one we have needed to date. Would accept a PR for that.

I disagree with point `3`... if you want different semantics, do not use `require`. The error message clearly states what the problem was, and by using `require` you're saying that its a terminal failure if the key cannot properly be loaded, so it seems to do the right thing. Sounds like you want `lookup` not `require`

I don't recall why we didn't add a `Configured[Long]`; probably just didn't need it as we're typically not configuring values more than Int.MAX_VALUE (i'd argue that it would not make sense to do that either, as it would be a bit of a non-sensical value most likely to anyone reading it after the fact).

**Comment by lambdista** [comment]
Hi @timperret, thank you for your answer. About the point 3 maybe I was not able to express what I mean. I'm not saying that it's not fair to throw an exception, I'm just saying that, in cases where the key is present but the value could have not been converted, the exception thrown is still *No such key* while the key is present and I suppose this is misleading. I think the exception should be thrown but be a different one such as `ConversionError`. See my REPL session where I differentiate the two exceptions. That said, we both agree on the fact that the most idiomatic way to walk through a configuration is using `lookup` and not `require`. :+1:

Furthermore, what do you think about point 1?

Thank you.

**Comment by timperrett** [comment]
@lambdista there's no particular reason AFAICR as to why we didn't implement a configured `Map`. @runarorama, can you shed some light? Also, we should probably add a `Configured[Long]` on reflection.

**Comment by richid** [comment]
Just jumping in here real quick to add a vote for `2` above. I'm building a custom TSC (that is, not simply using `ConfigFactory.load` so having a way to pass in an existing TSC instance would be very nice.

**Comment by timperrett** [comment]
Someone asked about this recently in Gitter, and I gave this answer: 

First and foremost, i’d like to say that people should use the tool that best fits their use case - if thats knobs, great, if its TC then thats fine too; we’re not trying to make an uber solution that solves all use cases. For us, that kind of “config” is really application data [...]. Config for us is usually a discrete set of data that informs the application about edge of world setup and provides default arguments and so forth - it is specifically not too powerful so that people don't do crazy config that is more like a program with it, as we had previously accumulated quite a bit of debt with people doing those kinds of things.

Most of the time, when folks want something like `Map`, I know that you’ll be loading all sorts of things at runtime. Given that a config is checked into source anyway, typically we would just prefer to do it in Scala and roll a new release of the code, as i'm sure you probably do with the config at which point its moot if the "config" is in config file or code - naturally the code is preferable, as its typechecked.

If you're operating a chef-style config management solution, and pushing pure-config changes to production, then it is highly likely that knobs is not a fit for you if you're relying on the config being quite powerful. We're doing immutable deployments, and our deployment system is pretty optimized for iterating on these kinds of things, so we just don't worry about it. 

Once again, if someone wants to send a PR for Map support, and it didn't get in the way of other things Knobs is doing, then we would absolutely consider merging it, but its not something that will need to add.

**Comment by lambdista** [comment]
@richid Timothy is right: "people should use the tool that best fits their use case". When I raised my concerns, after long time no response, I realised that they were just *my* concerns and not people's at OnCue given that, as I wrote in my first post, I had already implemented those 4 points in my forked version of knobs but they didn't seem too happy about me sending a PR and I didn't. That's perfectly reasonable for the motivations Timothy explained in the previous post.

However, seeing they were not interested in it, I *rmed* knobs and wrote a config library with the exact features I was looking for. Here it is [config](https://github.com/lambdista/config).  

Of course my library is far from being production ready and I suggest you use knobs or some other more mature config library. However, if you want to give it a spin and let me know what you think I'd be more than happy.

Cheers,
Alessandro

**Comment by timperrett** [comment]
@lambdista who did not seem happy about receiving a PR? If you have one ready, then sure, send it - as mentioned, we're always happy to accept contributions provided its inline with the rest of the project :-) I would never say "don't send that PR. don't try to contribute" - we always encourage contributions, but naturally cant guarantee that every PR would be merged (same as any other project).

Thanks for the interest. 

Best, Tim

**Comment by lambdista** [comment]
@timperrett I hesitated to send a PR because I was waiting for a reply to [this message of mine](https://github.com/oncue/knobs/issues/23#issuecomment-156496649), sent on Nov 13, 2015. I then got your reply on Dec 8, 2015 where you wrote: "there's no particular reason AFAICR as to why we didn't implement a configured `Map`. @runarorama, can you shed some light?". 

Afterward, I waited for a while but having seen no answer for months I deleted my work also because, meanwhile, I had written my config library with the exact features I needed. 

Maybe misunderstanding I thought: "no response for months" = "we're not interested, thank you". However, I hope you agree with me that I cannot be fully blamed for having _timed out_ the request. :-) 

Thanks for your reply.

Best,
Alessandro

**Comment by timperrett** [comment]
I don't place blame - and welcome contributions. There's no benefit in trying to scold anyone :-) We're pretty busy internally over here, so it just dropped off the backlog. There was and remains no ill intent from our side.

**Comment by lambdista** [comment]
No problem Tim, I do know there was no ill intent from your side. I just thought you were not interested in it and that would have been perfectly understandable. FTR, I love the work you and the rest of your team are doing.

Best,
Alessandro

**Comment by slouc** [comment]
@lambdista I don't see the reply to your point no. 3 from this issue, perhaps I'm missing something. I also agree that missing value and decoding error should not be flattened into one, both in require and lookup. Did you get an answer as to what's the reasoning behind this short-circuit?

**Comment by lambdista** [comment]
@slouc I think I got no reply for that, or maybe I missed it. However, as I wrote some message before, at some point I stopped waiting for replies and decided to write my own config lib from scratch, just to have some fun.
